AllCops:
  TargetRubyVersion: 4.0
  NewCops: disable
  DisabledByDefault: true
  SuggestExtensions: false
  UseCache: false
  Exclude:
    - "node_modules/**/*"
    - "vendor/**/*"
    - "website/node_modules/**/*"
    - "website/docs/.vitepress/cache/**/*"
    - "website/docs/.vitepress/dist/**/*"
    - "website/docs/.vitepress/.temp/**/*"

Layout:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint:
  Enabled: true
