module FiberStream
  class SchedulerRequiredError < RuntimeError
  end

  class Source[Elem]
    def self.each: [Elem] (Enumerable[Elem] enumerable) -> Source[Elem]
    def via: [Out] (Flow[Elem, Out] flow) -> Source[Out]
    def map: [Out] () { (Elem) -> Out } -> Source[Out]
    def select: () { (Elem) -> boolish } -> Source[Elem]
    def take: (Integer count) -> Source[Elem]
    def async: () -> Source[Elem]
    def buffer: (Integer count) -> Source[Elem]
    def run_with: [Mat] (Sink[Elem, Mat] sink) -> Mat
  end

  class Flow[In, Out]
    def self.map: [In, Out] () { (In) -> Out } -> Flow[In, Out]
    def self.select: [Elem] () { (Elem) -> boolish } -> Flow[Elem, Elem]
    def self.take: [Elem] (Integer count) -> Flow[Elem, Elem]
    def self.async: [Elem] () -> Flow[Elem, Elem]
    def self.buffer: [Elem] (Integer count) -> Flow[Elem, Elem]
  end

  class Sink[In, Mat]
    def self.to_a: [Elem] () -> Sink[Elem, Array[Elem]]
    def self.first: [Elem] () -> Sink[Elem, Elem?]
    def self.fold: [Elem, Acc] (Acc initial) { (Acc, Elem) -> Acc } -> Sink[Elem, Acc]
  end
end
